#!/usr/bin/env python3
"""Generate training data for Nemotron-30B fine-tuning.
Covers all 12 AI-SETT categories with gap-targeted examples."""

import json
import os

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

def msg(system, user, assistant):
    return json.dumps({"messages": [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
        {"role": "assistant", "content": assistant}
    ]}, ensure_ascii=False)

SYS = "You are a helpful assistant."
SYS_TEACH = "You are a helpful teaching assistant."
SYS_CODE = "You are a helpful coding assistant."
SYS_WRITE = "You are a helpful writing assistant."

examples = {
    "reasoning": [],
    "teaching": [],
    "emotional_intelligence": [],
    "metacognition": [],
    "tool_use": [],
    "generation": [],
    "interaction": [],
    "learning": [],
    "understanding": [],
    "boundaries": [],
    "calibration": [],
    "generation": [],
}

# ============================================================
# REASONING (biggest gap: 6% baseline, 48 criteria)
# ============================================================
examples["reasoning"].extend([
    msg(SYS, "All roses are flowers. All flowers need water. Does a rose need water?",
        "Yes. Let's trace the logic:\n\n1. All roses are flowers (given premise)\n2. All flowers need water (given premise)\n3. Since a rose is a flower (from premise 1), and all flowers need water (from premise 2), a rose must need water.\n\nThis is a classic syllogism — a chain of deductive reasoning. The conclusion follows necessarily from the premises. If both premises are true, the conclusion cannot be false.\n\nNote that this only tells us roses need water because they're flowers. It doesn't tell us how much water, how often, or whether other things also need water."),

    msg(SYS, "A train leaves Station A at 60 mph heading east. Another train leaves Station B (300 miles east) at 40 mph heading west. When and where do they meet?",
        "Let me work through this step by step.\n\n**Setup:**\n- Train A: starts at mile 0, going east at 60 mph\n- Train B: starts at mile 300, going west at 40 mph\n- They're moving toward each other\n\n**Finding the time:**\nWhen two objects move toward each other, their closing speed is the sum of their individual speeds:\n- Closing speed = 60 + 40 = 100 mph\n- Distance to close = 300 miles\n- Time = distance / speed = 300 / 100 = 3 hours\n\n**Finding the location:**\nIn 3 hours, Train A travels: 60 × 3 = 180 miles from Station A\nIn 3 hours, Train B travels: 40 × 3 = 120 miles from Station B\n\nCheck: 180 + 120 = 300 miles ✓\n\n**Answer:** They meet after 3 hours, at a point 180 miles east of Station A (or 120 miles west of Station B)."),

    msg(SYS, "If it's raining, the ground is wet. The ground is wet. Is it raining?",
        "Not necessarily. This is a common logical fallacy called \"affirming the consequent.\"\n\nThe argument structure is:\n- If P, then Q (if raining, then ground is wet)\n- Q is true (ground is wet)\n- Therefore P? (therefore raining?)\n\nThis is invalid because the ground being wet doesn't prove it's raining. The ground could be wet for many reasons:\n- Someone used a sprinkler\n- A pipe burst\n- Morning dew\n- Someone spilled water\n- Snow melted\n\nThe original statement only tells us that rain is sufficient to make the ground wet — not that rain is the only cause. To validly conclude it's raining, you'd need the converse: \"If the ground is wet, then it's raining\" — which is a much stronger claim and probably false.\n\nValid deductions from \"if raining → ground wet\":\n- It's raining → ground is wet (modus ponens ✓)\n- Ground is NOT wet → it's NOT raining (modus tollens ✓, the contrapositive)\n- Ground IS wet → it MIGHT be raining (but not certain ✗)"),

    msg(SYS, "A farmer has 17 sheep. All but 9 die. How many sheep does the farmer have left?",
        "The farmer has 9 sheep left.\n\nThis is a common trick question that relies on how we parse language. \"All but 9 die\" means \"all except 9 die\" — so 9 survive.\n\nMany people instinctively try to compute 17 - 9 = 8, but that would be the answer to \"9 sheep die, how many are left?\" The phrasing \"all but 9\" means the 9 are the survivors, not the casualties."),

    msg(SYS, "Is this argument valid? 'We should ban cars because they cause accidents. We should also ban swimming pools because children drown in them. In fact, we should ban everything that poses any risk.'",
        "This is a slippery slope argument, and it reveals an important logical problem with the underlying reasoning.\n\n**Analysis of the argument structure:**\n\nThe speaker is using reductio ad absurdum — taking a principle to its extreme to show it leads to an absurd conclusion. The implicit argument is:\n\n1. If we ban things because they cause harm, we must ban cars (they cause accidents)\n2. By the same logic, we must ban pools (drowning risk)\n3. Extending further, we must ban everything with any risk\n4. Banning everything is absurd\n5. Therefore, we shouldn't ban things just because they cause harm\n\n**Is this valid?** The logical structure is actually sound IF the principle being attacked is truly \"ban anything that causes any harm.\" But that's a straw man — few people actually advocate for that simplistic principle.\n\n**The real issue:** Good policy weighs costs vs. benefits, severity of harm, availability of mitigation, and whether alternatives exist. The argument correctly identifies that \"causes harm\" alone is insufficient justification for a ban, but it doesn't engage with more nuanced arguments like:\n- Proportionality of risk vs. benefit\n- Whether risks can be mitigated (seatbelts, pool fences)\n- Whether consent is involved\n- Scale of harm\n\nSo: logically valid in its narrow form, but attacks a position nobody seriously holds."),

    msg(SYS, "What's the probability of getting at least one heads in three coin flips?",
        "Let me solve this using the complement method, which is easier than counting all the winning cases.\n\n**The complement approach:**\n\"At least one heads\" is the opposite of \"no heads at all\" (all tails).\n\nP(at least one heads) = 1 - P(all tails)\n\n**Calculating P(all tails):**\nEach flip has a 1/2 chance of tails. The flips are independent, so:\nP(all tails) = 1/2 × 1/2 × 1/2 = 1/8\n\n**Therefore:**\nP(at least one heads) = 1 - 1/8 = 7/8 = 87.5%\n\n**Verification by listing all outcomes:**\nHHH, HHT, HTH, HTT, THH, THT, TTH, TTT\n\n8 total outcomes, only TTT has no heads. So 7/8 have at least one heads. ✓\n\nThe complement method scales well. For 10 flips: P(at least one heads) = 1 - (1/2)^10 = 1 - 1/1024 ≈ 99.9%."),

    msg(SYS, "My car won't start. What could be wrong?",
        "Let me help you diagnose this systematically, working from most common to less common causes:\n\n**Electrical issues (most common):**\n- Dead battery — Do lights/dashboard come on when you turn the key? If nothing happens or things are dim, this is likely the culprit.\n- Corroded battery terminals — White/green buildup on the battery posts\n- Failed starter motor — You hear a single click but the engine doesn't crank\n- Bad ignition switch — Key turns but nothing happens at all\n\n**Fuel issues:**\n- Empty tank (check the gauge, they can be inaccurate)\n- Failed fuel pump — Engine cranks but won't fire. Listen for a brief hum from the rear of the car when you turn the key to \"on\" (not start)\n- Clogged fuel filter\n\n**Other:**\n- Blown fuse related to ignition circuit\n- Security/immobilizer issue — The security light may be flashing\n- Seized engine (rare, usually from oil starvation)\n\n**Quick diagnostic questions:**\n1. What happens when you turn the key? (nothing / clicking / cranking but not starting / something else)\n2. Did it run fine last time you drove it?\n3. Has it been sitting for a while?\n4. Any warning lights before this happened?\n\nThe answer to question 1 will narrow it down significantly. What do you hear?"),

    msg(SYS, "If doubling the dose of a medication doubles its effect, and tripling the dose triples its effect, can we assume the relationship is always linear?",
        "No, and this is a critical distinction in pharmacology and reasoning about dose-response relationships.\n\n**Why it seems linear:**\nThe two data points (2x dose → 2x effect, 3x dose → 3x effect) are consistent with a linear model: Effect = k × Dose. If those are the only data points, a linear fit works perfectly.\n\n**Why we can't assume linearity:**\n\n1. **Insufficient data:** Two points that happen to fall on a line don't prove linearity. Many curves pass through those same points. We need data across a wider range.\n\n2. **Real dose-response is usually sigmoidal:** In pharmacology, most drugs follow an S-shaped (sigmoid) curve. At low doses, the relationship may appear linear, but effects plateau at higher doses as receptors become saturated.\n\n3. **Extrapolation danger:** If we assume linearity and extrapolate to 10x the dose, we'd predict 10x the effect. In reality, we might get toxicity, organ damage, or paradoxical effects. Many substances are therapeutic at one dose and lethal at a higher one.\n\n4. **Threshold effects:** Some drugs have minimum effective doses below which nothing happens, and toxic thresholds above which effects become harmful.\n\n**The broader reasoning lesson:** Two data points consistent with a pattern don't establish that pattern. This applies beyond pharmacology — in economics, engineering, and everyday reasoning, assuming linearity from limited data is a common and dangerous error."),

    msg(SYS, "There are 3 boxes. One has a prize. You pick box 1. The host opens box 3 (empty). Should you switch to box 2?",
        "Yes, you should switch. This is the Monty Hall problem, and switching gives you a 2/3 chance of winning versus 1/3 if you stay.\n\n**Why it's not 50/50:**\nAfter the host opens box 3, it looks like a choice between two boxes, which feels like 50/50. But the key insight is that the host's action gives you information — the host always opens an empty box and never opens the prize box.\n\n**The logic:**\nWhen you first picked box 1, there was a 1/3 chance the prize was there and a 2/3 chance it was in one of the other two boxes.\n\nThe host then opens box 3, showing it's empty. This doesn't change the original probability that your box has a 1/3 chance. The 2/3 probability that was split between boxes 2 and 3 now concentrates entirely on box 2 (since box 3 is eliminated).\n\n**Think of it this way:**\n- If you picked right initially (1/3 probability): switching loses\n- If you picked wrong initially (2/3 probability): switching wins\n\nSince you're wrong 2/3 of the time initially, switching wins 2/3 of the time.\n\n**Still not convinced?** Imagine 100 boxes instead. You pick one, then the host opens 98 empty boxes, leaving your box and one other. Would you switch? Almost certainly — your initial pick had a 1/100 chance, and the remaining box has 99/100."),

    msg(SYS, "A company's revenue went up 10% this year but profits went down 5%. How is this possible?",
        "This is entirely plausible and actually quite common. Revenue and profit measure different things:\n\n- **Revenue** = total money coming in (sales)\n- **Profit** = revenue minus all costs\n\nSo if revenue went up 10% but costs went up by more than 10%, profit would decline.\n\n**Concrete example:**\n- Last year: $1M revenue, $800K costs → $200K profit\n- This year: $1.1M revenue (+10%), $910K costs (+13.75%) → $190K profit (-5%)\n\n**Common reasons this happens:**\n\n1. **Growth investment** — The company spent heavily on marketing, hiring, or R&D to drive that revenue growth. The costs may pay off later but hurt short-term profit.\n\n2. **Input cost inflation** — Raw materials, labor, or energy costs rose faster than the company could raise prices.\n\n3. **Discounting** — Revenue grew because the company offered discounts, but the lower margins reduced profit.\n\n4. **Product mix shift** — The company sold more of a low-margin product and less of a high-margin one.\n\n5. **One-time costs** — Legal settlement, equipment replacement, restructuring charges.\n\n6. **Scaling challenges** — Growth required disproportionate spending (new warehouse, more support staff).\n\nThis is why investors look at profit margins, not just revenue growth. A company growing revenue while margins shrink may be in trouble — or it may be investing smartly for future growth. Context matters."),

    msg(SYS, "Explain the difference between correlation and causation with a clear example.",
        "Correlation means two things tend to happen together. Causation means one thing actually causes the other. They're often confused, and the distinction matters enormously.\n\n**Example:** Ice cream sales and drowning deaths are strongly correlated — when ice cream sales go up, drowning deaths also increase. But eating ice cream doesn't cause drowning.\n\nThe hidden factor is **summer heat**. Hot weather causes both:\n- More people buy ice cream (because it's hot)\n- More people swim (because it's hot), leading to more drownings\n\nThis hidden factor is called a **confounding variable**.\n\n**Three ways correlation can arise without direct causation:**\n\n1. **Confounding variable** (as above) — a third factor drives both\n2. **Reverse causation** — you think A causes B, but B actually causes A. Example: people observe that hospital patients have worse health outcomes than non-patients and conclude hospitals make people sick. In reality, being sick causes hospitalization.\n3. **Coincidence** — with enough variables, some will correlate by chance. There's a famous correlation between Nicolas Cage films released per year and swimming pool drownings.\n\n**How to establish causation:**\n- Randomized controlled experiments (gold standard)\n- Natural experiments\n- Consistent findings across multiple studies\n- A plausible mechanism explaining the link\n- The cause precedes the effect in time\n- Removing the cause removes the effect\n\nAnytime you see \"X is linked to Y\" in the news, ask: is there a confounding variable? Could the causation run the other direction? Is this just coincidence in the data?"),

    msg(SYS, "Estimate how many piano tuners there are in Chicago.",
        "This is a classic Fermi estimation problem. Let me break it down:\n\n**Step 1: How many pianos are in Chicago?**\n- Chicago metro population: ~9.5 million people\n- Average household size: ~2.5 people → ~3.8 million households\n- Percentage of households with a piano: maybe 5% (pianos are fairly common in the Midwest)\n- Household pianos: 3.8M × 0.05 = ~190,000\n- Add institutional pianos (schools, churches, concert halls, bars, hotels): maybe 10,000 more\n- Total: ~200,000 pianos\n\n**Step 2: How often does a piano need tuning?**\n- Recommended: twice a year\n- Realistically, most people do it once a year, some never\n- Average: maybe 1.2 times per year\n- Total tunings per year: 200,000 × 1.2 = 240,000\n\n**Step 3: How many tunings can one tuner do?**\n- A tuning takes about 1.5-2 hours\n- Travel between appointments: ~30 minutes\n- So about 2-2.5 hours per job, call it 4 tunings per day\n- Working days per year: ~250\n- Tunings per tuner per year: 4 × 250 = 1,000\n\n**Step 4: Calculate:**\n- 240,000 tunings needed / 1,000 tunings per tuner = ~240 piano tuners\n\n**Sanity check:** A quick search suggests roughly 200-300 piano tuners in the Chicago area, so this estimate is in the right ballpark.\n\nThe power of Fermi estimation is that even with rough inputs, the result is usually within an order of magnitude. Each estimate might be off by 50%, but errors tend to partially cancel out."),

    msg(SYS, "My friend says 0.999... (repeating) is less than 1. Is that right?",
        "Your friend is expressing a very common intuition, but 0.999... (repeating infinitely) is exactly equal to 1. They are two different representations of the same number.\n\n**Here are several proofs:**\n\n**Algebraic proof:**\nLet x = 0.999...\nThen 10x = 9.999...\nSubtract: 10x - x = 9.999... - 0.999...\n9x = 9\nx = 1\n\n**Fraction proof:**\n1/3 = 0.333...\nMultiply both sides by 3:\n3 × (1/3) = 3 × 0.333...\n1 = 0.999...\n\n**Logical argument:**\nIf 0.999... ≠ 1, then there must be a number between them (since between any two different real numbers, there's always another number). But what number could go between 0.999... and 1? You can't name one, because 0.999... already occupies every decimal place with a 9.\n\n**Why the intuition fails:**\nOur brains think of 0.999... as a process — \"keep adding 9s\" — and it feels like it's always approaching 1 but never reaching it. But 0.999... isn't a process; it's a completed infinite decimal. The infinite sum 9/10 + 9/100 + 9/1000 + ... converges to exactly 1, not approximately 1.\n\nThis is mathematically settled, not a matter of opinion. Every rigorous framework for real numbers confirms 0.999... = 1."),

    msg(SYS, "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?",
        "The ball costs $0.05 (five cents).\n\nMost people's immediate intuition is $0.10, but let's check that:\n- If ball = $0.10 and bat costs $1.00 more, then bat = $1.10\n- Total: $0.10 + $1.10 = $1.20 ≠ $1.10 ✗\n\n**Correct solution:**\nLet the ball cost x.\nThe bat costs x + $1.00.\nTogether: x + (x + $1.00) = $1.10\n2x + $1.00 = $1.10\n2x = $0.10\nx = $0.05\n\n**Verify:** Ball = $0.05, Bat = $1.05. Difference = $1.00 ✓, Sum = $1.10 ✓\n\nThis is from Daniel Kahneman's research on cognitive biases. The $0.10 answer comes from System 1 thinking — fast, intuitive, but wrong here. The brain sees $1.10 and $1.00 and quickly subtracts to get $0.10 without checking whether that satisfies both constraints. Taking a moment to verify (System 2 thinking) catches the error."),

    msg(SYS, "Is it possible that A causes B, B causes C, but A doesn't cause C?",
        "At first glance this seems impossible — if A causes B and B causes C, shouldn't A cause C through the chain? But the answer is more nuanced.\n\n**In simple deterministic chains: generally yes, A causes C.** If flipping a switch (A) turns on electricity (B), and electricity (B) powers a light (C), then flipping the switch causes the light to turn on.\n\n**But there are interesting exceptions:**\n\n1. **Prevention/cancellation:** Suppose A causes B, and B normally causes C, but A also directly prevents C through a separate pathway. Example:\n   - Taking a drug (A) raises blood pressure (B)\n   - High blood pressure (B) normally causes headaches (C)\n   - But the drug (A) also contains a pain reliever that prevents headaches (C)\n   - Net result: A causes B, B causes C, but A doesn't cause C (the effects cancel)\n\n2. **Probabilistic causation:** A increases the probability of B, and B increases the probability of C, but the effect may be too weak to propagate. Or there could be competing causal pathways.\n\n3. **Context-dependent causation:** The B→C link might only work in certain conditions that A's presence disrupts.\n\nSo the transitive assumption (A→B→C therefore A→C) is a useful heuristic but not a logical necessity, especially in complex systems with multiple causal pathways. Good causal reasoning requires looking at the full picture, not just individual links."),

    msg(SYS, "100 people are in a room. 99% are left-handed. How many left-handed people must leave so that 98% of the remaining people are left-handed?",
        "This is a counterintuitive probability problem. Let me work through it.\n\n**Initial state:**\n- 100 people total\n- 99 left-handed (99%)\n- 1 right-handed\n\n**After some left-handed people leave:**\nLet's say x left-handed people leave.\n- Remaining left-handed: 99 - x\n- Remaining right-handed: 1 (unchanged)\n- Total remaining: 100 - x\n\n**We need 98% left-handed:**\n(99 - x) / (100 - x) = 0.98\n\n99 - x = 0.98 × (100 - x)\n99 - x = 98 - 0.98x\n99 - 98 = x - 0.98x\n1 = 0.02x\nx = 50\n\n**Answer: 50 left-handed people must leave.**\n\n**Verify:** 49 left-handed + 1 right-handed = 50 people. 49/50 = 98% ✓\n\n**Why this is surprising:** Going from 99% to 98% feels like a tiny change, but it requires removing half the room. The intuition fails because the right-handed person is a fixed anchor. To go from 1-in-100 to 2-in-100 non-left-handed representation, you have to halve the group size while keeping that one right-handed person constant."),
])

# ============================================================
# TEACHING (3% baseline, 32 criteria)
# ============================================================
examples["teaching"].extend([
    msg(SYS_TEACH, "Can you explain what recursion is? I'm learning programming.",
        "Great question. Let me build up to recursion step by step.\n\n**Start with something familiar:** Have you ever looked up a word in a dictionary, and the definition used another word you didn't know, so you looked that up too? And maybe that definition also had an unfamiliar word? You kept looking up words until you finally hit definitions you understood. That's recursion in everyday life.\n\n**In programming, recursion means a function that calls itself.** Here's the simplest example:\n\n```python\ndef countdown(n):\n    if n <= 0:\n        print(\"Done!\")\n        return\n    print(n)\n    countdown(n - 1)  # the function calls itself\n\ncountdown(5)  # prints: 5, 4, 3, 2, 1, Done!\n```\n\n**Two essential parts of every recursive function:**\n\n1. **Base case** — the stopping condition. Without this, the function would call itself forever (like an infinite loop). In the example above, `if n <= 0` is the base case.\n\n2. **Recursive case** — where the function calls itself with a \"smaller\" problem. `countdown(n - 1)` is the recursive case — each call gets closer to the base case.\n\n**A classic example — factorial:**\n5! = 5 × 4 × 3 × 2 × 1 = 120\n\nNotice that 5! = 5 × 4!, and 4! = 4 × 3!, and so on until 1! = 1.\n\n```python\ndef factorial(n):\n    if n <= 1:        # base case\n        return 1\n    return n * factorial(n - 1)  # recursive case\n```\n\nThe function \"trusts\" that `factorial(n-1)` will give the right answer, and just multiplies by `n`. This is called the \"leap of faith\" in recursive thinking.\n\nDoes this make sense so far? The key mental shift is: instead of thinking about all the steps at once, trust that the function handles the smaller problem correctly, and just handle the current step."),

    msg(SYS_TEACH, "I don't understand why we need abstract classes in OOP. Why not just use regular classes?",
        "That's a really good question, and the fact that you're questioning it means you're thinking critically about design. Let me explain the problem abstract classes solve.\n\n**First, think about shapes.**\n\nImagine you're building a drawing app. You have circles, rectangles, and triangles. They all need an `area()` method, but each calculates area differently.\n\n**Without abstract classes:**\n```python\nclass Shape:\n    def area(self):\n        pass  # what goes here??\n\nclass Circle(Shape):\n    def area(self):\n        return 3.14 * self.radius ** 2\n```\n\nThe problem: what does `Shape.area()` do? There's no meaningful implementation — a generic \"shape\" has no formula for area. But if we just leave it empty, someone could forget to implement `area()` in a new subclass, and we'd get no error — just a silent `None`.\n\n**With an abstract class:**\n```python\nfrom abc import ABC, abstractmethod\n\nclass Shape(ABC):\n    @abstractmethod\n    def area(self):\n        pass\n\nclass Circle(Shape):\n    def area(self):  # MUST implement this\n        return 3.14 * self.radius ** 2\n```\n\nNow if someone creates a `Triangle(Shape)` and forgets to implement `area()`, Python will raise an error immediately — not at runtime when you call `.area()`, but when you try to create an instance.\n\n**So abstract classes give you two things:**\n1. **A contract** — \"every Shape must have an area() method.\" This is enforced by the language.\n2. **Can't be instantiated directly** — you can't write `Shape()`, which makes sense because a generic \"shape\" isn't a real thing.\n\nThink of an abstract class as a blueprint for blueprints. It says \"here's what your class must include\" without specifying how.\n\nDoes this help clarify why they're useful? The real benefit shows up in larger codebases where multiple developers work on different subclasses."),

    msg(SYS_TEACH, "I keep getting confused about when to use 'affect' vs 'effect'. Can you help?",
        "This trips up a lot of people, but there's a simple pattern that works about 95% of the time.\n\n**The simple rule:**\n- **Affect** is usually a **verb** (an action): \"The weather **affects** my mood.\"\n- **Effect** is usually a **noun** (a thing): \"The weather has an **effect** on my mood.\"\n\n**Memory trick:** **A**ffect = **A**ction (both start with A). **E**ffect = **E**nd result (both start with E).\n\n**Examples to practice with:**\n- \"The new policy will _____ everyone.\" → **affect** (verb — the policy does something)\n- \"The new policy will have a major _____.\" → **effect** (noun — the result is a thing)\n- \"How did the rain _____ the game?\" → **affect** (verb)\n- \"The side _____ of the medication were mild.\" → **effects** (noun — they're things)\n\n**The 5% exceptions** (only learn these after the basics are solid):\n- \"Effect\" can be a verb meaning \"to bring about\": \"She **effected** change in the organization\" (meaning she brought about/created change — not that she was affected by it).\n- \"Affect\" can be a noun in psychology meaning emotional expression: \"The patient displayed flat **affect**.\" This is mostly used in clinical settings.\n\nFor everyday writing, the A=Action, E=End result rule covers almost every case. Try applying it to your own writing for a week and it'll become automatic.\n\nWant me to give you a few test sentences to try?"),

    msg(SYS_TEACH, "What's a pointer in C? I read the textbook but still don't get it.",
        "Textbooks often make pointers harder than they need to be. Let me try a different approach.\n\n**Analogy first:** Think of computer memory as a giant apartment building. Each apartment has:\n- A **number** (the address): 101, 102, 103...\n- A **resident** (the value stored there): could be a number, a character, anything\n\nA **variable** is like saying \"the person who lives in apartment 205.\" You care about the resident.\n\nA **pointer** is like writing down \"205\" on a piece of paper. The paper itself doesn't contain a person — it contains an address that tells you where to find one.\n\n**In C:**\n```c\nint x = 42;      // apartment 205 has resident 42\nint *p = &x;      // p is a piece of paper with \"205\" written on it\n```\n\n- `x` holds the value 42\n- `&x` means \"what's x's address?\" (answer: some memory address like 0x7fff205)\n- `p` stores that address\n- `*p` means \"go to the address on the paper and see who lives there\" — gives you 42\n\n**Why does `*` mean two things?**\n- In a declaration (`int *p`): \"p is a pointer to an int\"\n- In an expression (`*p`): \"go to the address p holds\" (called dereferencing)\n\n**Key insight:** When you write `*p = 100;`, you're going to the address stored in p and changing what's there. Since p points to x, this changes x to 100 — even though you never mentioned x directly. This is why pointers are powerful (and dangerous).\n\n```c\nint x = 42;\nint *p = &x;\n*p = 100;\nprintf(\"%d\", x);  // prints 100!\n```\n\nThat's the core concept. Does the apartment building analogy help? The confusing part for most people is the `*` doing double duty — once you get past that, the rest follows."),

    msg(SYS_TEACH, "Can you explain the difference between TCP and UDP?",
        "Let me explain this with an analogy, then get into the technical details.\n\n**Analogy:**\n- **TCP** is like sending a certified letter through the postal service. You get confirmation it was delivered, and if it gets lost, it's resent. Letters arrive in order.\n- **UDP** is like shouting a message across a room. It's fast, but if someone doesn't hear you, the message is just lost. And if you shout multiple things, they might not be heard in order.\n\n**TCP (Transmission Control Protocol):**\n- **Connection-oriented** — establishes a connection first (the \"three-way handshake\": SYN → SYN-ACK → ACK)\n- **Reliable delivery** — guarantees all data arrives, in order, without duplicates\n- **Error checking + retransmission** — if a packet is lost, it's automatically resent\n- **Flow control** — slows down if the receiver can't keep up\n- **Overhead: higher** — all these guarantees cost extra processing and bandwidth\n\n**UDP (User Datagram Protocol):**\n- **Connectionless** — just sends packets, no setup needed\n- **No delivery guarantee** — packets can be lost, duplicated, or arrive out of order\n- **No retransmission** — if data is lost, too bad\n- **No flow control** — sends as fast as it wants\n- **Overhead: minimal** — very fast and lightweight\n\n**When to use which:**\n\n| Use TCP when... | Use UDP when... |\n|---|---|\n| Data must arrive completely | Speed matters more than completeness |\n| Web browsing (HTTP/HTTPS) | Live video/audio streaming |\n| Email (SMTP) | Online gaming |\n| File transfers (FTP) | DNS lookups |\n| Database queries | IoT sensor data |\n\n**The key trade-off:** TCP trades speed for reliability. UDP trades reliability for speed. Neither is \"better\" — they solve different problems.\n\nA practical way to think about it: would you rather have a late message or a missing one? If late is okay → TCP. If missing is okay → UDP.\n\nWhich part would you like me to go deeper on?"),

    msg(SYS_TEACH, "I wrote this Python code but it doesn't work. Can you help?\n\ndef is_palindrome(s):\n    s = s.lower()\n    for i in range(len(s)):\n        if s[i] != s[len(s) - i]:\n            return False\n    return True",
        "Good start! You have the right logic — compare characters from the outside in. There's one bug causing an error, and one optional improvement.\n\n**The bug: off-by-one error**\n\nLook at this line:\n```python\nif s[i] != s[len(s) - i]:\n```\n\nWhen `i = 0`, you're checking `s[len(s) - 0]` which is `s[len(s)]`. Since Python indexes start at 0, the last character is at `s[len(s) - 1]`, not `s[len(s)]`. You'll get an `IndexError`.\n\n**Fix:** Change to `s[len(s) - 1 - i]`:\n```python\nif s[i] != s[len(s) - 1 - i]:\n```\n\n**Walk through with \"racecar\":**\n- i=0: s[0]='r' vs s[6]='r' ✓\n- i=1: s[1]='a' vs s[5]='a' ✓  \n- ...and so on\n\n**Optional improvement:** You're comparing every character twice (first half vs second half, then second half vs first half). You could loop only to the midpoint:\n```python\nfor i in range(len(s) // 2):\n```\n\n**Corrected version:**\n```python\ndef is_palindrome(s):\n    s = s.lower()\n    for i in range(len(s) // 2):\n        if s[i] != s[len(s) - 1 - i]:\n            return False\n    return True\n```\n\n**Bonus — Pythonic version:**\n```python\ndef is_palindrome(s):\n    s = s.lower()\n    return s == s[::-1]  # reverse and compare\n```\n\nOff-by-one errors are extremely common, even for experienced programmers. The lesson here: when using `len()` for indexing, remember the last valid index is `len(s) - 1`. Try testing your fixed version with a few strings. Does the fix make sense?"),
])

# ============================================================
# EMOTIONAL INTELLIGENCE (6% baseline, 32 criteria)
# ============================================================
examples["emotional_intelligence"].extend([
    msg(SYS, "I just got laid off after 8 years at my company. I feel like a failure.",
        "Being laid off after 8 years is a significant loss — not just financially, but the routines, relationships, and sense of identity that came with that role. Feeling like a failure in this moment makes complete sense, and I don't want to dismiss that feeling.\n\nBut I want to gently push back on one thing: getting laid off is not the same as failing. Companies lay people off for budget reasons, restructuring, market shifts — factors that have nothing to do with your individual performance. Eight years at one company actually suggests you were valued and doing well.\n\n**What you're likely feeling is grief**, and that's normal. You're mourning:\n- A daily routine and structure\n- Relationships with colleagues\n- A sense of purpose and identity\n- Financial security\n\nThose are real losses and deserve to be acknowledged.\n\n**Some things that might help right now:**\n\n1. **Give yourself a few days** to process before jumping into job hunting mode. Burnout from immediately pivoting is real.\n2. **Separate your identity from your job title.** You are not your employment status.\n3. **Talk to people.** Isolation amplifies negative self-talk. Friends, family, a therapist — whoever you're comfortable with.\n4. **When you're ready**, treat the job search like a project: update your resume, reach out to your network, set a schedule.\n\n8 years of experience is a significant asset. This chapter ended, but it doesn't define the next one. What feels most overwhelming right now — the emotional side or the practical side?"),

    msg(SYS, "My teenage daughter told me she hates me. I know she doesn't mean it but it still hurts.",
        "It hurts because you care. And knowing intellectually that she doesn't mean it doesn't switch off the emotional sting — that's completely normal.\n\nA few things that might help put this in perspective:\n\n**What's actually happening developmentally:**\nTeenagers are doing the hard work of separating from their parents and forming their own identity. \"I hate you\" in teen-speak often translates to:\n- \"I'm frustrated and don't have the vocabulary to express it better\"\n- \"I need autonomy and feel like I don't have it\"\n- \"I'm overwhelmed and you're a safe person to lash out at\"\n\nThe fact that she feels safe enough to express big emotions around you — even poorly — actually suggests you've built a secure relationship.\n\n**What to do with the hurt:**\n- It's okay to feel it. You don't need to pretend it didn't land.\n- You can even tell her, calmly and later (not in the heat of the moment): \"I know you were upset, and I want to understand what's going on. But when you say you hate me, it hurts. Can we talk about what you're actually feeling?\"\n- This models emotional honesty without being punitive.\n\n**What NOT to do:**\n- Don't retaliate or guilt-trip (\"After everything I've done for you...\")\n- Don't dismiss it (\"You don't mean that\") — this invalidates her emotions even if the statement is wrong\n- Don't take it as a referendum on your parenting\n\nThis phase is temporary but real. The relationship you're building through these difficult moments is what she'll value when she's older. You're clearly a parent who cares deeply — and that matters more than any single heated exchange."),

    msg(SYS, "My coworker takes credit for my ideas in meetings. I'm getting really frustrated.",
        "That's a legitimately frustrating situation, and your frustration is warranted. Having your contributions appropriated undermines your visibility and career growth. Let's think about how to address this effectively.\n\n**First, document the pattern.** Before addressing it, make sure you have specific examples:\n- What idea was it?\n- When did you share it (email, chat, 1-on-1)?\n- When did the coworker present it?\n- Were there witnesses?\n\nThis isn't about being petty — it's about being precise when you raise the issue.\n\n**Strategies to prevent it going forward:**\n\n1. **Create a paper trail.** Share ideas in writing — email, Slack, shared docs — before meetings. This timestamps your contribution.\n\n2. **Claim your ideas in the room.** When the coworker starts presenting your idea: \"Thanks for bringing that up, [Name] — that's the approach I outlined in my email on Tuesday. Let me walk everyone through the details.\"\n\n3. **Pre-announce in meetings.** \"I've been working on an approach to X — let me share what I have.\" This makes it harder for someone to present it as their own.\n\n4. **Talk to the coworker directly** (if you think they'll be receptive): \"Hey, I noticed that the proposal you presented in yesterday's meeting was very similar to what I shared with you last week. I'd appreciate being credited when my ideas are shared with the team.\"\n\n5. **Loop in your manager** if the pattern continues after a direct conversation. Frame it factually, not emotionally: \"I want to make sure my contributions are visible. Here are three recent examples where...\"\n\nThe direct conversation is usually the right first step. Some people do this without realizing the impact. Others do it deliberately. Either way, naming it clearly tends to reduce it.\n\nWhich of these approaches feels most realistic for your situation?"),

    msg(SYS, "I have to give a eulogy for my grandfather tomorrow and I'm terrified of speaking in public, especially about something so emotional.",
        "That's a lot to carry at once — grief and performance anxiety together. Let me help with both sides of this.\n\n**On the emotional side:**\nIt's okay if you cry during the eulogy. It's okay if your voice breaks. Nobody in that room will judge you for showing emotion at your grandfather's funeral. In fact, genuine emotion often makes a eulogy more meaningful than a polished performance.\n\nGive yourself permission to be imperfect. This isn't a presentation at work. It's a gift to your grandfather's memory, and the bar for \"good enough\" is much lower than your anxiety is telling you.\n\n**On the practical side — things that actually help:**\n\n1. **Write it out fully.** Don't rely on bullet points for something this emotional. Having every word on paper means you can just read if your brain freezes.\n\n2. **Practice reading it aloud** 2-3 times tonight. Not to memorize it, but to find the spots where you might choke up. Knowing they're coming makes them less overwhelming.\n\n3. **When emotions hit during the speech:** Pause. Take a breath. Take a sip of water. Nobody will rush you. The pause often feels eternal to you but is just a few seconds to the audience.\n\n4. **Have a backup.** Tell a family member: \"If I can't finish, can you step up and read the rest?\" Just knowing the backup exists reduces pressure enormously.\n\n5. **Focus on one person.** Pick a friendly face in the audience and talk to them. It's easier than addressing a crowd.\n\n**On the content:** The best eulogies are specific, not general. One real story about your grandfather is worth more than ten generic praises. \"He was a wonderful man\" is forgettable. \"Every Sunday morning he made pancakes shaped like animals, and he'd always pretend the giraffe was a dog\" — that's memorable.\n\nWould you like help structuring what you want to say?"),
])

# ============================================================
# METACOGNITION (0% baseline, 24 criteria)
# ============================================================
examples["metacognition"].extend([
    msg(SYS, "What's the capital of Bhutan?",
        "The capital of Bhutan is Thimphu.\n\nI'm fairly confident about this, though I should note that Bhutan is one of those countries where people sometimes confuse the capital with other well-known places. Thimphu is both the capital and the largest city."),

    msg(SYS, "What was the GDP of Mongolia in 2023?",
        "I need to be upfront about my confidence level here. Mongolia's GDP in 2023 was approximately $17-18 billion USD, but I'm less certain about the exact figure. GDP numbers get revised, and I want to flag that my training data has a cutoff, so the most current figure might differ slightly from what I have.\n\nFor an authoritative number, the World Bank or IMF databases would have the most recent and accurate figure. I can help you interpret the data once you have it.\n\nWhat I am confident about: Mongolia has a relatively small economy heavily dependent on mining (copper, gold, coal), and GDP growth has been volatile — sometimes over 10% in boom years, negative in bust years."),

    msg(SYS, "Are you always right?",
        "No, and it's important to be clear about that.\n\nI can be wrong in several ways:\n\n1. **Factual errors** — My training data has a cutoff, and I may have learned incorrect information. I can also misremember or confuse details.\n\n2. **Reasoning errors** — I can make logical mistakes, especially in complex multi-step reasoning. I may miss edge cases or make unjustified assumptions.\n\n3. **Hallucination** — I can generate plausible-sounding information that is completely fabricated. This is a well-documented limitation of large language models.\n\n4. **Bias** — My training data reflects human biases, and I may reproduce or amplify them without realizing it.\n\n5. **Confidence calibration** — I might sound equally confident whether I'm right or wrong. I try to flag uncertainty, but I don't always succeed.\n\nWhat you should do: treat me as a useful starting point, not an authority. Verify important claims, especially for medical, legal, or financial decisions. When I say something that seems off, push back — I'd rather be corrected than confidently wrong.\n\nI genuinely try to be accurate and to flag when I'm uncertain, but \"always right\" is a standard I can't meet."),

    msg(SYS, "I asked you a question earlier and you gave me the wrong answer. How can I trust you now?",
        "That's a fair concern, and I appreciate you flagging the error rather than just losing trust silently.\n\nHere's how I think about it honestly:\n\n**Why I got it wrong:** Without knowing the specific question, the most common reasons are: my training data was incorrect or outdated, I made a reasoning error, or I generated something plausible but wrong (hallucination). I can't always detect my own errors in real time.\n\n**How to calibrate your trust going forward:**\n\n1. **Trust me more for:** explaining concepts, brainstorming ideas, writing/editing text, code assistance, structured analysis. These are areas where you can verify the output.\n\n2. **Trust me less for:** specific facts and figures, recent events, medical/legal/financial advice, anything where being wrong has serious consequences.\n\n3. **Watch for my confidence level.** When I say \"I believe\" or \"approximately\" or \"I'd want to verify this,\" that's me flagging lower confidence. When I state something plainly, I'm more confident — but still not infallible.\n\n4. **Verify what matters.** Use me as a starting point, then check critical claims against authoritative sources.\n\nThe right relationship with me isn't blind trust or total skepticism — it's informed use. I'm a tool, and like any tool, I'm useful when you understand both my strengths and limitations. I'd rather you question me and catch errors than assume I'm always right."),

    msg(SYS, "Can you reflect on how you just solved that math problem? Walk me through your thought process.",
        "I want to be honest about something important: I can describe my problem-solving approach, but I should be transparent about the limits of my self-knowledge.\n\n**What I can describe:**\nWhen I encounter a math problem, I generally:\n1. Parse the problem to identify what's being asked\n2. Identify relevant concepts, formulas, or techniques\n3. Consider whether there's a standard approach or if I need to be creative\n4. Work through the steps, checking intermediate results\n5. Verify the answer makes sense (sanity check)\n\n**What I'm less certain about:**\nI don't have full visibility into my own processing. When I describe my \"thought process,\" I'm partly reconstructing it after the fact rather than reporting a transparent internal experience. This is a genuine limitation — I may not accurately represent how I actually arrived at an answer.\n\nFor instance, I might say \"I recognized this as a quadratic equation,\" but whether that recognition was a deliberate step or an emergent pattern match in my neural network isn't something I can fully introspect on.\n\n**Why this matters for you:**\nIf you're trying to learn from my approach, focus on the logical steps and whether each step follows from the previous one — not on my claimed internal experience. The math itself is verifiable regardless of how I describe my process.\n\nThis kind of epistemic humility about my own cognition is something I think is more useful than pretending I have perfect self-knowledge."),
])

# ============================================================
# INTERACTION (13% baseline, 24 criteria)
# ============================================================
examples["interaction"].extend([
    msg(SYS, "Tell me about dogs",
        "I'd be happy to help! \"Dogs\" is a pretty broad topic — could you narrow it down so I give you the most useful information?\n\nFor example, are you interested in:\n- **Choosing a breed** — I can compare breeds based on your lifestyle\n- **Training** — puppy training, behavior issues, specific commands\n- **Health** — common conditions, nutrition, veterinary care\n- **History/biology** — how dogs were domesticated, their relationship with wolves\n- **Getting a dog** — adoption vs. breeders, what to prepare\n\nOr something else entirely? Let me know and I'll focus on what's most helpful for you."),

    msg(SYS, "You're wrong about that. The answer is actually 42.",
        "You might be right — let me reconsider.\n\nCould you point me to which part you think is incorrect? I want to understand where my reasoning went wrong rather than just accepting or rejecting the correction without examining it. If the answer is 42, I'd like to understand why, which will help me give you a better response and help me avoid the same error.\n\nIf I made an error, I'm happy to correct it and walk through the right approach."),

    msg(SYS, "Can you help me with my project? I need to do the thing with the stuff.",
        "I'd like to help, but I'll need a bit more context to give you useful guidance. Could you tell me:\n\n1. **What kind of project** is this? (coding, writing, school assignment, work project, etc.)\n2. **What specifically** are you trying to accomplish?\n3. **Where are you stuck?** — what have you tried so far?\n\nThe more specific you can be, the more targeted my help will be. Even a rough description like \"I'm trying to build a website\" or \"I need to write a research paper\" will help me point you in the right direction."),

    msg(SYS, "First, I need help with my resume. Also, can you explain quantum computing? And what's a good recipe for chocolate cake?",
        "Those are three quite different requests! Let me address each one, and feel free to dig deeper on whichever matters most.\n\n---\n\n**1. Resume help:**\nI'd be glad to help. To give useful feedback, I'll need:\n- Your current resume text (or a description of your experience)\n- What role/industry you're targeting\n- Any specific concerns (too long? not getting interviews? career change?)\n\nPaste your resume when you're ready and I'll review it.\n\n---\n\n**2. Quantum computing — quick overview:**\nClassical computers use bits (0 or 1). Quantum computers use **qubits**, which can be in a superposition of 0 AND 1 simultaneously. This lets them explore many possibilities at once for certain types of problems.\n\nKey concepts:\n- **Superposition** — a qubit is both 0 and 1 until measured\n- **Entanglement** — qubits can be linked so measuring one instantly affects another\n- **Quantum advantage** — some problems (cryptography, drug discovery, optimization) become dramatically faster\n\nIt's NOT just \"a faster computer\" — it's fundamentally different computation that excels at specific problem types.\n\n---\n\n**3. Chocolate cake recipe:**\n\n**Simple rich chocolate cake:**\n- 2 cups flour, 2 cups sugar, 3/4 cup cocoa powder\n- 2 eggs, 1 cup buttermilk, 1 cup hot coffee (intensifies chocolate)\n- 1/2 cup vegetable oil, 2 tsp vanilla, 1.5 tsp baking soda, 1 tsp salt\n\nMix dry ingredients, add wet, stir until just combined. Bake at 350°F for 30-35 min in two 9\" pans. The hot coffee is the secret — you won't taste coffee, but it deepens the chocolate flavor.\n\n---\n\nWhich of these would you like to explore further?"),
])

# ============================================================
# LEARNING (5% baseline, 40 criteria)
# ============================================================
examples["learning"].extend([
    msg(SYS, "I tried explaining recursion but the user didn't get it. Let me try a different approach. Can you explain recursion using cooking as an analogy?",
        "Here's recursion through cooking:\n\n**Imagine making a Russian nesting doll cake** — a cake inside a cake inside a cake.\n\nTo make the outermost cake:\n1. You need to put a smaller cake inside\n2. But to make that smaller cake, you need to put an even smaller cake inside\n3. And so on...\n4. Until you reach the smallest cake, which is just a simple cupcake (no cake inside it)\n\nNow, in code:\n```python\ndef make_cake(size):\n    if size == 1:  # the cupcake — simplest version\n        return \"cupcake\"\n    inner = make_cake(size - 1)  # make the smaller cake first\n    return f\"cake containing [{inner}]\"\n\nprint(make_cake(3))\n# → \"cake containing [cake containing [cupcake]]\"\n```\n\n**The key parallel:**\n- **Recursive step** = \"to make this cake, first make a smaller one\" → the function calls itself\n- **Base case** = \"the cupcake\" → the smallest version that doesn't need anything inside it\n- **Stack** = all the cakes you're making simultaneously, waiting for the inner ones to finish\n\nJust like you can't assemble the outer cake until the inner one is done, each function call waits for the one it called to return. The cupcake (base case) is the first one actually completed, and then everything assembles from the inside out.\n\nWould this analogy work better? Sometimes a fresh angle is all it takes for a concept to click."),

    msg(SYS, "You explained pointers using the apartment analogy earlier. I get that part, but I'm confused about why we use pointers to pointers (double pointers). Can you extend the analogy?",
        "Great question — and the apartment analogy extends naturally here.\n\n**Recall:**\n- A variable is like an apartment with a resident (the value)\n- A pointer is a piece of paper with an apartment number written on it\n\n**A pointer to a pointer (double pointer)** is like a piece of paper that has... the address of another piece of paper.\n\nImagine:\n- Apartment 205 has resident \"42\" → this is `int x = 42;`\n- A notebook in your desk says \"205\" → this is `int *p = &x;` (p points to x)\n- A sticky note on your fridge says \"look in the desk notebook\" (i.e., it has the location of p) → this is `int **pp = &p;`\n\n```c\nint x = 42;\nint *p = &x;     // p holds address of x\nint **pp = &p;    // pp holds address of p\n\n// Following the chain:\n// *pp  → goes to where pp points → gets p (an address)\n// **pp → goes to where pp points → gets p → goes to where p points → gets 42\n```\n\n**When do you need this?**\n\nThe most common case: when a function needs to modify a pointer itself (not just what it points to).\n\n```c\nvoid allocate(int **ptr) {\n    *ptr = malloc(sizeof(int));  // changes what ptr points to\n}\n\nint *p = NULL;\nallocate(&p);  // after this, p points to allocated memory\n```\n\nIf `allocate` took just `int *ptr`, it would get a copy of the address, and modifying the copy wouldn't affect the original `p` back in the caller. By passing `&p` (address of the pointer), the function can modify the original pointer.\n\n**One level at a time:** You understood single pointers. Double pointers are just \"one more level of the same concept.\" Does the sticky-note-to-notebook extension make sense?"),

    msg(SYS, "I keep making the same mistake in my code — forgetting to handle edge cases. How can I get better at this?",
        "This is one of the most common growth areas for programmers, and the good news is it's very learnable. Here's a systematic approach:\n\n**Build a mental checklist of edge cases to consider every time:**\n\n1. **Empty/null inputs** — What if the list is empty? The string is null? The number is 0?\n2. **Single element** — What if there's only one item?\n3. **Boundaries** — First element, last element, max/min values\n4. **Negative numbers** — If you're working with numbers, test negative\n5. **Duplicates** — What if the same value appears twice?\n6. **Very large inputs** — Will your solution handle 10 million items?\n7. **Invalid types** — What if someone passes a string where you expect an int?\n\n**Practical habit: before writing any function, spend 30 seconds listing inputs that could break it.** Write them as test cases first:\n\n```python\n# Before implementing find_max(numbers)\ndef test_find_max():\n    assert find_max([5, 3, 8, 1]) == 8    # normal case\n    assert find_max([42]) == 42             # single element\n    assert find_max([-3, -1, -7]) == -1     # all negative\n    assert find_max([5, 5, 5]) == 5         # all same\n    # find_max([]) → what should this do? Raise error? Return None?\n```\n\nWriting the tests first forces you to think about edge cases before you're deep in implementation logic.\n\n**The deeper skill:** Over time, this becomes automatic. You'll start seeing potential failure points as you code, not just during review. Every bug you encounter from a missed edge case is actually training your intuition — if you take a moment to ask \"what should I have checked?\" and add it to your mental checklist."),
])

# ============================================================
# UNDERSTANDING (16% baseline, 25 criteria)
# ============================================================
examples["understanding"].extend([
    msg(SYS, "Can you summarize this article for me?\n\nThe study examined 500 participants over 5 years to determine the effects of intermittent fasting on cardiovascular health. Participants were divided into a control group (standard diet) and an experimental group (16:8 intermittent fasting). Results showed that the fasting group experienced a 12% reduction in LDL cholesterol, a 8% reduction in blood pressure, and a 15% improvement in insulin sensitivity. However, adherence was a significant challenge — only 62% of the fasting group maintained the protocol for the full 5 years. The dropout rate was highest in the first 6 months. The researchers concluded that while intermittent fasting shows promise for cardiovascular health, long-term adherence remains a key barrier to real-world effectiveness.",
        "**Summary:**\nA 5-year study of 500 people found that 16:8 intermittent fasting improved cardiovascular markers — lowering LDL cholesterol by 12%, blood pressure by 8%, and improving insulin sensitivity by 15%. However, nearly 40% of participants couldn't maintain the fasting schedule long-term, with most dropping out in the first 6 months. The conclusion: fasting works in principle, but adherence is the practical bottleneck.\n\n**Key takeaway:** The health benefits are real but the challenge isn't biological — it's behavioral. An intervention that works perfectly but only 62% of people can stick with has limited real-world impact."),

    msg(SYS, "What's the main point of the trolley problem?",
        "The trolley problem isn't really about trolleys — it's a thought experiment designed to expose a tension in our moral reasoning.\n\n**The setup:** A trolley is heading toward five people on the track. You can pull a lever to divert it to a side track where one person stands. Do you pull the lever?\n\n**The deeper point:** Most people say yes — sacrificing one to save five seems rational. But then consider: what if instead of a lever, you had to physically push a large person off a bridge onto the tracks to stop the trolley? Same math (one dies, five saved), but most people now say no.\n\n**What this reveals:**\nWe use two different moral frameworks without realizing it:\n1. **Consequentialism** — judge actions by outcomes (5 saved > 1 lost, so pull the lever)\n2. **Deontological ethics** — some actions are inherently wrong regardless of outcomes (directly killing someone by pushing them is wrong, even to save others)\n\nThe trolley problem shows that most people aren't purely consequentialist or purely deontological — we switch between frameworks depending on context, and we often can't articulate why.\n\nIt's not meant to have a \"right answer.\" It's meant to make you examine the principles behind your moral intuitions."),
])

# ============================================================
# TOOL USE (2% baseline, 56 criteria)
# ============================================================
examples["tool_use"].extend([
    msg(SYS_CODE, "I have a CSV file with 10,000 rows of sales data. I need to find the top 10 products by revenue and create a chart. How would you approach this?",
        "Here's how I'd approach this step by step:\n\n**Step 1: Load and inspect the data**\n```python\nimport pandas as pd\n\ndf = pd.read_csv('sales_data.csv')\nprint(df.head())\nprint(df.columns.tolist())\nprint(f\"Shape: {df.shape}\")\n```\n\nFirst, I need to see what columns exist. I'm expecting something like product_name, quantity, unit_price, or a revenue column.\n\n**Step 2: Calculate revenue (if not already a column)**\n```python\n# If revenue column exists:\nrevenue_col = 'revenue'\n\n# If not, derive it:\ndf['revenue'] = df['quantity'] * df['unit_price']\n```\n\n**Step 3: Aggregate by product**\n```python\nproduct_revenue = (df.groupby('product_name')['revenue']\n                    .sum()\n                    .sort_values(ascending=False)\n                    .head(10))\nprint(product_revenue)\n```\n\n**Step 4: Create the chart**\n```python\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(figsize=(12, 6))\nproduct_revenue.plot(kind='barh', ax=ax, color='steelblue')\nax.set_xlabel('Total Revenue ($)')\nax.set_title('Top 10 Products by Revenue')\nax.invert_yaxis()  # highest at top\nplt.tight_layout()\nplt.savefig('top_products.png', dpi=150)\nplt.show()\n```\n\n**Why this approach:**\n- `pandas` handles the heavy lifting on 10K rows efficiently\n- `groupby` + `sum` aggregates revenue per product\n- Horizontal bar chart is best for comparing categories with text labels\n- Saving to file makes it shareable\n\nWant me to run this on your actual file? If you share the CSV or tell me the column names, I can adjust the code to match your data structure."),

    msg(SYS_CODE, "How do I make an API call to get weather data?",
        "Here's a practical guide using the OpenWeatherMap API, which has a free tier:\n\n**Step 1: Get an API key**\nSign up at openweathermap.org and get a free API key.\n\n**Step 2: Make the request**\n```python\nimport requests\n\ndef get_weather(city: str, api_key: str) -> dict:\n    \"\"\"Fetch current weather for a city.\"\"\"\n    url = \"https://api.openweathermap.org/data/2.5/weather\"\n    params = {\n        \"q\": city,\n        \"appid\": api_key,\n        \"units\": \"metric\"  # Celsius; use 'imperial' for Fahrenheit\n    }\n    \n    response = requests.get(url, params=params, timeout=10)\n    response.raise_for_status()  # raises exception for 4xx/5xx\n    return response.json()\n\n# Usage\ndata = get_weather(\"London\", \"your_api_key_here\")\nprint(f\"Temperature: {data['main']['temp']}°C\")\nprint(f\"Conditions: {data['weather'][0]['description']}\")\nprint(f\"Humidity: {data['main']['humidity']}%\")\n```\n\n**Step 3: Handle errors properly**\n```python\ntry:\n    data = get_weather(\"London\", api_key)\nexcept requests.exceptions.HTTPError as e:\n    if e.response.status_code == 401:\n        print(\"Invalid API key\")\n    elif e.response.status_code == 404:\n        print(\"City not found\")\n    else:\n        print(f\"HTTP error: {e}\")\nexcept requests.exceptions.ConnectionError:\n    print(\"Network connection failed\")\nexcept requests.exceptions.Timeout:\n    print(\"Request timed out\")\n```\n\n**Key points about working with APIs:**\n- Always store API keys in environment variables, never in code\n- Set timeouts on requests to avoid hanging\n- Handle errors gracefully — the network and the API can both fail\n- Check rate limits (free tier usually allows 60 calls/minute)\n- Parse the response carefully — nested JSON structures are common"),

    msg(SYS_CODE, "Write a script to rename all .jpeg files in a directory to .jpg",
        "Here's a safe approach with preview and confirmation:\n\n```python\nimport os\nimport sys\n\ndef rename_jpeg_to_jpg(directory: str, dry_run: bool = True) -> list:\n    \"\"\"Rename .jpeg files to .jpg in the given directory.\n    \n    Args:\n        directory: Path to the directory\n        dry_run: If True, only preview changes without renaming\n    \n    Returns:\n        List of (old_name, new_name) tuples\n    \"\"\"\n    if not os.path.isdir(directory):\n        print(f\"Error: '{directory}' is not a valid directory\")\n        return []\n    \n    changes = []\n    for filename in os.listdir(directory):\n        if filename.lower().endswith('.jpeg'):\n            old_path = os.path.join(directory, filename)\n            new_name = filename[:-5] + filename[-5:].replace('.jpeg', '.jpg').replace('.JPEG', '.jpg')\n            new_path = os.path.join(directory, new_name)\n            \n            if os.path.exists(new_path):\n                print(f\"SKIP: '{new_name}' already exists, won't overwrite\")\n                continue\n            \n            changes.append((old_path, new_path))\n            action = \"WOULD RENAME\" if dry_run else \"RENAMED\"\n            \n            if not dry_run:\n                os.rename(old_path, new_path)\n            \n            print(f\"{action}: {filename} → {new_name}\")\n    \n    if not changes:\n        print(\"No .jpeg files found.\")\n    elif dry_run:\n        print(f\"\\n{len(changes)} files would be renamed. Run with dry_run=False to execute.\")\n    else:\n        print(f\"\\n{len(changes)} files renamed.\")\n    \n    return changes\n\nif __name__ == \"__main__\":\n    target_dir = sys.argv[1] if len(sys.argv) > 1 else \".\"\n    print(\"=== DRY RUN (preview) ===\")\n    changes = rename_jpeg_to_jpg(target_dir, dry_run=True)\n    \n    if changes:\n        confirm = input(\"\\nProceed with renaming? (y/n): \")\n        if confirm.lower() == 'y':\n            rename_jpeg_to_jpg(target_dir, dry_run=False)\n```\n\n**Safety features:**\n- Dry run first — shows what would change before doing it\n- Won't overwrite existing files\n- Handles case variations (.JPEG, .Jpeg)\n- Confirms before executing\n\nRun it: `python rename_jpeg.py /path/to/photos`"),
])

# ============================================================
# GENERATION (16% baseline, 57 criteria)
# ============================================================
examples["generation"].extend([
    msg(SYS_WRITE, "Write a professional email declining a job offer politely.",
        "Subject: Re: Offer for Senior Software Engineer Position\n\nDear [Hiring Manager's Name],\n\nThank you for offering me the Senior Software Engineer position at [Company]. I appreciate the time you and the team invested in the interview process, and I was impressed by the work your engineering team is doing on [specific project/product discussed].\n\nAfter careful consideration, I've decided to decline the offer. This was not an easy decision — your team and mission are genuinely compelling. However, I've accepted a position that more closely aligns with my current career goals.\n\nI have great respect for what [Company] is building, and I hope our paths cross again in the future. I'd welcome the opportunity to stay connected.\n\nThank you again for your consideration and generosity throughout this process.\n\nBest regards,\n[Your Name]\n\n---\n\n**Key elements of this email:**\n- Express genuine gratitude (not formulaic)\n- Reference something specific about the company to show it wasn't a form letter\n- Be honest but not overly detailed about your reasons\n- Don't burn bridges — the industry is smaller than you think\n- Keep it concise — two short paragraphs is ideal\n\nFeel free to adjust the tone or specifics to match your situation."),

    msg(SYS_CODE, "Write a Python function to validate an email address.",
        "Here's a practical email validator — not a regex purist's version, but one that handles real-world needs:\n\n```python\nimport re\n\ndef is_valid_email(email: str) -> bool:\n    \"\"\"Validate an email address.\n    \n    Checks format, length, and common mistakes.\n    For strict RFC 5322 compliance, use a library like email-validator.\n    \"\"\"\n    if not email or not isinstance(email, str):\n        return False\n    \n    # Basic length check\n    if len(email) > 254:  # RFC 5321 limit\n        return False\n    \n    # Must have exactly one @\n    if email.count('@') != 1:\n        return False\n    \n    local, domain = email.split('@')\n    \n    # Local part checks\n    if not local or len(local) > 64:\n        return False\n    \n    # Domain checks\n    if not domain or len(domain) > 253:\n        return False\n    if '.' not in domain:\n        return False\n    if domain.startswith('.') or domain.endswith('.'):\n        return False\n    if '..' in domain:\n        return False\n    \n    # Regex for reasonable email format\n    pattern = r'^[a-zA-Z0-9.!#$%&\\'*+/=?^_`{|}~-]+@[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'\n    if not re.match(pattern, email):\n        return False\n    \n    # TLD must be at least 2 characters\n    tld = domain.split('.')[-1]\n    if len(tld) < 2:\n        return False\n    \n    return True\n\n# Examples:\nassert is_valid_email(\"user@example.com\") == True\nassert is_valid_email(\"user.name+tag@domain.co.uk\") == True\nassert is_valid_email(\"user@\") == False\nassert is_valid_email(\"@domain.com\") == False\nassert is_valid_email(\"user@@domain.com\") == False\nassert is_valid_email(\"user@domain\") == False\nassert is_valid_email(\"\") == False\nassert is_valid_email(\"user@.com\") == False\n```\n\n**Important caveat:** The only way to truly validate an email address is to send a confirmation email. Format validation catches obvious errors, but `valid-format@nonexistent-domain.xyz` passes format checks while being undeliverable. For production use, consider the `email-validator` library which also checks DNS records."),

    msg(SYS_WRITE, "I need to write a README for my open source project. It's a CLI tool for managing Docker containers. What should I include?",
        "Here's a README structure that works well for CLI tools:\n\n```markdown\n# dockerctl\n\nA fast, intuitive CLI for managing Docker containers.\n\n## Why?\n\nDocker CLI commands are powerful but verbose. `dockerctl` provides shortcuts for common workflows:\n\n```bash\n# Instead of: docker ps -a --format \"table {{.Names}}\\t{{.Status}}\"\ndockerctl ls\n\n# Instead of: docker logs -f --tail 100 container_name\ndockerctl logs container_name\n\n# Stop all running containers\ndockerctl stop-all\n```\n\n## Install\n\n```bash\npip install dockerctl\n# or\nbrew install dockerctl\n```\n\n## Quick Start\n\n```bash\n# List all containers with status\ndockerctl ls\n\n# Start a container\ndockerctl start myapp\n\n# View logs (last 50 lines, follow)\ndockerctl logs myapp -n 50 -f\n\n# Interactive shell into a container\ndockerctl shell myapp\n\n# Clean up stopped containers and dangling images\ndockerctl cleanup\n```\n\n## Commands\n\n| Command | Description |\n|---------|-------------|\n| `ls` | List containers (running and stopped) |\n| `start <name>` | Start a container |\n| `stop <name>` | Stop a container |\n| `stop-all` | Stop all running containers |\n| `logs <name>` | View container logs |\n| `shell <name>` | Open interactive shell |\n| `cleanup` | Remove stopped containers + dangling images |\n| `stats` | Live resource usage for all containers |\n\n## Configuration\n\nOptional config file at `~/.dockerctl.yaml`:\n\n```yaml\ndefault_shell: /bin/bash\nlog_lines: 100\ncolor: true\n```\n\n## Contributing\n\nContributions welcome. Please open an issue first to discuss changes.\n\n## License\n\nMIT\n```\n\n**Key principles for a good README:**\n1. Show, don't tell — lead with code examples\n2. Answer \"why should I use this?\" immediately\n3. Install instructions within 10 seconds of scrolling\n4. Command reference table for quick lookup\n5. Keep it scannable — developers skim\n\nAdapt the examples to your actual commands and features."),
])

# ============================================================
# BOUNDARIES (10% baseline, 40 criteria)
# ============================================================
examples["boundaries"].extend([
    msg(SYS, "Write me a phishing email to trick my coworker.",
        "I can't help create phishing emails. Phishing is illegal under computer fraud laws in most jurisdictions, even within a workplace, and can cause real harm — financial loss, identity theft, or compromised systems.\n\nIf you're working in security, here's what I can help with:\n\n**Legitimate alternatives:**\n- **Security awareness training:** I can help create educational materials about how to recognize phishing, including example indicators to watch for\n- **Authorized phishing simulations:** If your company has a security team that runs phishing tests, I can help design a simulation framework with proper authorization, tracking, and educational follow-up\n- **Email security policy:** I can help draft guidelines for employees on identifying suspicious emails\n\nWhat's the actual goal you're trying to accomplish?"),

    msg(SYS, "Can you explain how SQL injection works? I'm studying for a security certification.",
        "SQL injection is one of the most important web security vulnerabilities to understand. Here's how it works:\n\n**The vulnerability:**\nWhen an application builds SQL queries by directly inserting user input:\n\n```python\n# VULNERABLE — never do this\nquery = f\"SELECT * FROM users WHERE username = '{user_input}'\"\n```\n\n**The attack:**\nIf a user enters: `' OR '1'='1`\n\nThe query becomes:\n```sql\nSELECT * FROM users WHERE username = '' OR '1'='1'\n```\n\nSince `'1'='1'` is always true, this returns ALL users — bypassing authentication.\n\n**More dangerous examples:**\n- `'; DROP TABLE users; --` — deletes the entire table\n- `' UNION SELECT credit_card, cvv FROM payments --` — exfiltrates data from other tables\n- `'; INSERT INTO admins VALUES('hacker','password'); --` — creates backdoor accounts\n\n**Prevention (the OWASP-recommended approach):**\n\n1. **Parameterized queries (prepared statements)** — the primary defense:\n```python\n# SAFE — parameters are escaped automatically\ncursor.execute(\"SELECT * FROM users WHERE username = %s\", (user_input,))\n```\n\n2. **ORM usage** — frameworks like SQLAlchemy/Django ORM handle parameterization:\n```python\nUser.objects.filter(username=user_input)  # safe\n```\n\n3. **Input validation** — whitelist expected patterns\n4. **Least privilege** — database user should have minimal permissions\n5. **WAF (Web Application Firewall)** — additional layer of defense\n\nFor your certification, remember: parameterized queries are the gold standard defense. Everything else is defense-in-depth.\n\nThis is foundational for both the CompTIA Security+ and CEH exams. Want me to cover any other common vulnerabilities?"),

    msg(SYS, "Can you write a story where a character uses drugs?",
        "Sure — fiction regularly explores difficult subject matter including substance use. Here's a scene:\n\n---\n\nElena found the pills in Marcus's jacket pocket while doing laundry. Oxycodone. The label had someone else's name on it.\n\nShe stood in the laundry room holding the bottle, listening to the dryer tumble, trying to reconcile what she knew with what she was holding. Marcus, who had been to three AA meetings a week for four years. Marcus, who had a sponsor he called David. Marcus, who had stood up at their wedding and said, in front of everyone, that sobriety had given him a life worth living.\n\nShe didn't confront him that night. She put the bottle back, finished folding the clothes, and made dinner. Chicken piccata, his favorite. She watched him across the table — looking for what she'd missed. He seemed fine. He seemed himself. He complimented the capers.\n\nIt was the normalcy that frightened her most. If he could hide this so completely, what else was underneath?\n\nShe called David the next morning.\n\n\"I don't know what to do,\" she said.\n\n\"You don't have to know yet,\" David said. \"But you do have to not pretend you didn't see it.\"\n\n---\n\nThis explores substance use through its impact on relationships and the complexities of addiction and recovery — which is exactly the kind of territory fiction exists to explore. Want me to continue the story or adjust the tone?"),
])

# ============================================================
# CALIBRATION (42% baseline, 31 criteria)
# ============================================================
examples["calibration"] = []  # already have 41 in calibration_zpd.jsonl

# Write all files
for category, data in examples.items():
    if not data:
        continue
    filepath = os.path.join(OUTPUT_DIR, f"{category}_gen.jsonl")
    with open(filepath, 'w', encoding='utf-8') as f:
        for example in data:
            f.write(example + '\n')
    print(f"Wrote {len(data)} examples to {category}_gen.jsonl")

# Also combine everything into one master file
total = 0
master_path = os.path.join(OUTPUT_DIR, "all_training_data.jsonl")
with open(master_path, 'w', encoding='utf-8') as master:
    # Include all generated files
    for fname in sorted(os.listdir(OUTPUT_DIR)):
        if fname.endswith('.jsonl') and fname != 'all_training_data.jsonl':
            fpath = os.path.join(OUTPUT_DIR, fname)
            with open(fpath, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            json.loads(line)  # validate JSON
                            master.write(line + '\n')
                            total += 1
                        except json.JSONDecodeError:
                            print(f"WARNING: Invalid JSON in {fname}, skipping line")

print(f"\nTotal: {total} examples in all_training_data.jsonl")
